# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "11812fa95b561ddd68bf6857d66fcbea"
application_url = "https://wherever-sierra-capitol-calcium.trycloudflare.com"
embedded = true
name = "erinbellstore"
handle = "erinbellstore"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wherever-sierra-capitol-calcium.trycloudflare.com/auth/callback",
  "https://wherever-sierra-capitol-calcium.trycloudflare.com/auth/shopify/callback",
  "https://wherever-sierra-capitol-calcium.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
